---
title: "Sample-Usage"
date: "`r Sys.Date()`"
---

Sample usages from package functions


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# exampleDataR
```{r setup}
# sample data
library(Rinvent)
head(exampleDataR)
```

# maR 
``` {r}
library(Rinvent)
exampleDataR= data.table::as.data.table(exampleDataR)
exampleDataR = exampleDataR[order(location,item,date)]
exampleDataR[,ma5:= maR(sales,4),list(location,item)]
head(exampleDataR,10)
```

# readparquetR
``` {r}
temp <- tempfile()
arrow::write_parquet(mtcars, paste(temp,".parquet"))
readparquetR(paste(temp,".parquet"))

readparquetR(pathtoread=paste(temp,".parquet"), sample=T)

readparquetR(pathtoread=paste(temp,".parquet"), 
             collist = c("mpg","cyl","vs"),
             format="parquet",
             where="cyl==4 & vs!='0'")

```



# date_to_yyyymmdd
``` {r}
date_to_yyyymmdd("2022-02-28")
date_to_yyyymmdd("02/28/2022")
date_to_yyyymmdd("28.02.2022")
date_to_yyyymmdd("Feb 28, 2022")
date_to_yyyymmdd("28.02.2022", smart_format = F ,forceformat="%d.%m.%Y" )
```










